---
- name: Update esmbot
  hosts: bots.funkymonks.xyz
  gather_facts: true
  remote_user: fleabot
  tasks:

  - name: Update repository
    shell: git pull master
    args:
      chdir: /home/fleabot/fleabot


  - name: Rebuild application
    shell: npm install && npm run build
    args:
      chdir:  /home/fleabot/fleabot

  - name: Run application
    shell: pm2 restart dist/fleabot.js
    args:
      chdir: /home/fleabot/fleabot
