---
- name: Update esmbot
  hosts: bots.funkymonks.xyz
  gather_facts: true
  remote_user: fleabot
  tasks:

  - name: Update repository
    git:
      repo: 'https://github.com/Funky-Monks/fleabot'
      dest: /home/fleabot/fleabot
      force: yes

  - name: Run application
    shell: pm2 restart dist/fleabot.js
    args:
      chdir: /home/fleabot/fleabot
