name: deploy-master

on:
  push:

jobs:
  deploy-to-bots_funkymonks_xyz:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install ansible

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run playbook
      run: ansible-playbook ./.github/workflows/ansible/update-fleabot-playbook.yml -vvv -i ./.github/workflows/ansible/inventory.yml

    - name: Send CS start update message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.CS_DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.CS_DISCORD_WEBHOOK_TOKEN }}
        username: Fleabot updates
        args: Fleabot is being updated. Stay tuned...

    - name: Send CS end update message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.CS_DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.CS_DISCORD_WEBHOOK_TOKEN }}
        username: Fleabot updates
        args: Fleabot update is finished!