name: deploy-master

on:
  push:
    branches:
      - master

jobs:
  deploy-to-bots_funkymonks_xyz:
    runs-on: ubuntu-latest
    steps:
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: ./ansible/update-fleabot-playbook.yml
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        inventory: |
          [bots.funkymonks.xyz]
          5.161.130.142
