name: deploy-master

on:
  push:
    branches:
      - master

jobs:
  deploy-to-bots_funkymonks_xyz:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install ansible

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_bots
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa_bots.pub
        diff <( ssh-keygen -y -e -f "~/.ssh/id_rsa_bots" ) <( ssh-keygen -y -e -f "~/.ssh/id_rsa_bots.pub" )
        chmod 400 ~/.ssh/id_rsa.*

    - name: Run playbook
      working-directory: ./.github/workflows/ansible
      run: ansible-playbook update-fleabot-playbook.yml -vvv -i inventory.yml --key-file "~/.ssh/id_rsa_bots"

    - name: Send CS start update message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.CS_DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.CS_DISCORD_WEBHOOK_TOKEN }}
        username: Fleabot updates
        args: Fleabot is being updated. Stay tuned...

    - name: Send CS end update message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.CS_DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.CS_DISCORD_WEBHOOK_TOKEN }}
        username: Fleabot updates
        args: Fleabot update is finished!